name: higgins_server
version: 0.5.0-dev
author: The Pink Team
description: Server part of the Higgins CI tool
environment:
  sdk: '>=0.6.9'
dependencies:
  objectory: '>=0.3.8 <0.3.9'
  pathos: '>=0.6.3'
  route: '>=0.4.5 <0.4.6'
dev_dependencies:
  dartmocks: '>=0.4.1 <0.4.2'
  hop: '>=0.24.1 <0.24.2'
  unittest: '>=0.6.9'
