name: higgins_server
version: 0.5.0
author: The Pink Team
description: Server part of the Higgins CI tool
environment:
  sdk: '>=0.5.5'
dependencies:
  objectory: 0.3.1
  route: 0.4.5
dev_dependencies:
  unittest: '>=0.5.5'
  dartmocks: 0.4.0
  hop: '>=0.22.1+1 <0.22.2'  
