name: higgins_server
version: 0.5.0-dev
author: The Pink Team
description: Server part of the Higgins CI tool
environment:
  sdk: '>=0.5.16'
dependencies:
  objectory: '>=0.3.4 <0.3.5'
  route: '>=0.4.5 <0.4.6'
dev_dependencies:
  dartmocks: '>=0.4.1 <0.4.2'
  hop: '>=0.22.2 <0.22.3'
  unittest: '>=0.5.13'
